### PR TITLE
Fix bug that would connect GitHub to web apps instead of slot

### LINKED ISSUE #80: GitHub connection always connects to the web app even if initialized on a slot
Forgot to check to see if the site is a slot or web app.

### PR DESCRIPTION
**Pull request by nturinski**
Fixes #80 

Added aka.ms link for GitHub documentation
Changed response from taking user to portal to taking them to documentation to set it up.

### CODE REVIEW

File: appservice/src/SiteWrapper.ts [hunk 1]
```diff
@@ -584,14 +590,18 @@ export class SiteWrapper {
             isMercurial: false
         };
 
-        this.log(outputChannel, `"${this.appName}" is being connected to GitHub repo. This may take several minutes...`);
+        this.log(outputChannel, `"${this.appName}" is being connected to the GitHub repo. This may take several minutes...`);
         try {
-            await client.webApps.createOrUpdateSourceControlWithHttpOperationResponse(this.resourceGroup, this.name, siteSourceControl);
+            await this.updateSourceControl(client, siteSourceControl);
```
Comment (EricJizbaMSFT) [inline appservice/src/SiteWrapper.ts]: Do you think we'll always have to do a resync after updating source control? In other words, should updateSourceControl handle the resync or is it fine to have connectToGitHub handle the resync?

File: appservice/src/SiteWrapper.ts [hunk 2]
```diff
@@ -602,12 +612,13 @@ export class SiteWrapper {
         }
     }
 
-    private async showGitHubAuthPrompt(node: IAzureNode): Promise<void> {
-        const goToPortal: string = localize('goToPortal', 'Go to Portal');
-        const setupGithub: string = localize('GitRequired', 'Authorize Azure for GitHub under "Deployment options."');
+    private async showGitHubAuthPrompt(): Promise<void> {
+        const goToPortal: string = localize('learnMore', 'Learn More');
```
Comment (EricJizbaMSFT) [inline appservice/src/SiteWrapper.ts]: nit: rename the variable to learnMore

File: appservice/src/SiteWrapper.ts [hunk 3]
```diff
@@ -602,12 +612,13 @@ export class SiteWrapper {
...
+        const setupGithub: string = localize('GitRequired', 'Connect your App to a GitHub repository to authorize Azure.');
```
Comment (EricJizbaMSFT) [inline appservice/src/SiteWrapper.ts]: How about: "You must give Azure access to your Github account."

I think it sounds more like an error message and I think it makes it more obvious that you only have to do this once per account (rather than once per repository)

File: appservice/src/SiteWrapper.ts [hunk 4]
```diff
@@ -584,14 +590,18 @@ export class SiteWrapper {
...
+        this.log(outputChannel, `"${this.appName}" is being connected to the GitHub repo. This may take several minutes...`);
         try {
-            await client.webApps.createOrUpdateSourceControlWithHttpOperationResponse(this.resourceGroup, this.name, siteSourceControl);
+            await this.updateSourceControl(client, siteSourceControl);
         } catch (err) {
             try {
                 // a resync will fix the first broken build
                 // https://github.com/projectkudu/kudu/issues/2277
-                await client.webApps.syncRepository(this.resourceGroup, this.name);
+                if (this.slotName) {
```
Comment (EricJizbaMSFT) [inline appservice/src/SiteWrapper.ts]: nit: How about you move this into a SiteWrapper.syncRepository method

File: appservice/src/SiteWrapper.ts (hunk 1 above)
Comment (nturinski) [reply appservice/src/SiteWrapper.ts]: The resync seems to be specifically an issue for connecting to GitHub.  When we support other sourceControls (such as Bitbucket), I think we can see if that resync will be necessary for every updateSourceControl.

File: appservice/src/SiteWrapper.ts (hunk 4 above)
Comment (nturinski) [reply appservice/src/SiteWrapper.ts]: I'm not sure where we'd use this anywhere else (which is why I didn't create its own method).
