### PR TITLE
auth: Fix some issues

### LINKED ISSUE #1542: auth: Azure subscriptions are not returned in alphabetical order
For consistency with Azure Account we should alphabetize the results before returning them.

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #1542

### CODE REVIEW

File: auth/src/VSCodeAzureSubscriptionProvider.ts [hunk 1]
```diff
@@ -65,10 +65,10 @@ export class VSCodeAzureSubscriptionProvider extends vscode.Disposable implement
      */
     public async getSubscriptions(filter: boolean = true): Promise<AzureSubscription[]> {
         const tenantIds = await this.getTenantFilters();
-        const tenantFilterNormalized = filter && !!tenantIds.length; // If the list is empty it is treated as "no filter"
+        const shouldFilterTenants = filter && !!tenantIds.length; // If the list is empty it is treated as "no filter"
```
Comment (bwateratmsft) [inline auth/src/VSCodeAzureSubscriptionProvider.ts:68]: Wanted to rename these two because the original names were terrible.

**Review by nturinski — APPROVED** [review]
