### PR TITLE
Add tests, fix sorting quickpick issues

### LINKED ISSUE #1145: The new quick pick sorting behavior is not working correctly for recently used items
The new quick pick sorting added in #1138 is not working correctly for recently-used items.

Old behavior:
image

The recently used "Testing 2" item is at the top, and hitting "Enter" selects it.

New behavior:
image

The recently used "Testing 2" item is _not_ at the top, and re-selecting it requires navigating down to it.

/cc @StephenWeatherford

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #1145

Also fixed some edge cases with suppressPersistence.

### CODE REVIEW

File: utils/src/userInput/showQuickPick.ts [hunk 1]
```diff
@@ -149,12 +150,11 @@ function getRecentlyUsedKey(options: types.IAzureQuickPickOptions): string | und
     return recentlyUsedKey;
 }
 
-async function initializePicks<TPick extends types.IAzureQuickPickItem<unknown>>(picks: TPick[] | Promise<TPick[]>, options: types.IAzureQuickPickOptions, groups: QuickPickGroup[], recentlyUsedKey: string | undefined): Promise<TPick[]> {
+export async function createQuickPickItems<TPick extends types.IAzureQuickPickItem<unknown>>(picks: TPick[] | Promise<TPick[]>, options: types.IAzureQuickPickOptions, groups: QuickPickGroup[], recentlyUsedKey: string | undefined, globalState?: Memento): Promise<TPick[]> {
```
Comment (bwateratmsft) [inline utils/src/userInput/showQuickPick.ts:153]: Maybe worth a comment to note that this is exported only for the benefit of tests. Perhaps the same for the `globalState` param.

**Review by bwateratmsft — DISMISSED** [review]

File: utils/src/userInput/showQuickPick.ts (hunk 1 above)
Comment (StephenWeatherford) [reply utils/src/userInput/showQuickPick.ts]: done

**Review by bwateratmsft — APPROVED** [review]
